"""rework callback usage

Revision ID: affe444aad73
Revises: 807733b6fb80
Create Date: 2022-05-06 16:19:54.003056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'affe444aad73'
down_revision = '807733b6fb80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('callbacks', sa.Column('url', sa.String(length=255), nullable=False))
    op.add_column('callbacks', sa.Column('shared_secret', sa.String(length=2047), nullable=True))
    op.drop_column('callbacks', 'password')
    op.drop_column('callbacks', 'username')
    op.drop_column('callbacks', 'base')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('callbacks', sa.Column('base', sa.VARCHAR(length=255), nullable=False))
    op.add_column('callbacks', sa.Column('username', sa.VARCHAR(length=255), nullable=True))
    op.add_column('callbacks', sa.Column('password', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('callbacks', 'shared_secret')
    op.drop_column('callbacks', 'url')
    # ### end Alembic commands ###
